// This file is auto-generated by @hey-api/openapi-ts

import type { LoginTestTokenResponse, UsersReadUsersResponse, UsersCreateUserResponse, UsersReadUserMeResponse, UsersUpdateUserMeResponse, UsersRegisterUserResponse, UsersReadUserByIdResponse, UsersUpdateUserResponse, AuthorsReadAuthorsResponse, AuthorsCreateAuthorResponse, AuthorsReadAuthorMeResponse, AuthorsUpdateAuthorMeResponse, AuthorsReadAuthorByIdResponse, AuthorsUpdateAuthorResponse, PoemsReadPoemsResponse, PoemsCreatePoemResponse, PoemsReadPoemsMeResponse, PoemsReadPoemResponse, PoemsUpdatePoemResponse, PrivateCreateUserResponse } from './types.gen';

const userPublicSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    return data;
};

export const loginTestTokenResponseTransformer = async (data: any): Promise<LoginTestTokenResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

const usersPublicSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return userPublicSchemaResponseTransformer(item);
    });
    return data;
};

export const usersReadUsersResponseTransformer = async (data: any): Promise<UsersReadUsersResponse> => {
    data = usersPublicSchemaResponseTransformer(data);
    return data;
};

export const usersCreateUserResponseTransformer = async (data: any): Promise<UsersCreateUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersReadUserMeResponseTransformer = async (data: any): Promise<UsersReadUserMeResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersUpdateUserMeResponseTransformer = async (data: any): Promise<UsersUpdateUserMeResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersRegisterUserResponseTransformer = async (data: any): Promise<UsersRegisterUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersReadUserByIdResponseTransformer = async (data: any): Promise<UsersReadUserByIdResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersUpdateUserResponseTransformer = async (data: any): Promise<UsersUpdateUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

const poemPublicSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

const authorPublicWithPoemsSchemaResponseTransformer = (data: any) => {
    if (data.birth_date) {
        data.birth_date = new Date(data.birth_date);
    }
    if (data.poems) {
        data.poems = data.poems.map((item: any) => {
            return poemPublicSchemaResponseTransformer(item);
        });
    }
    return data;
};

const authorsPublicSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return authorPublicWithPoemsSchemaResponseTransformer(item);
    });
    return data;
};

export const authorsReadAuthorsResponseTransformer = async (data: any): Promise<AuthorsReadAuthorsResponse> => {
    data = authorsPublicSchemaResponseTransformer(data);
    return data;
};

export const authorsCreateAuthorResponseTransformer = async (data: any): Promise<AuthorsCreateAuthorResponse> => {
    data = authorPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const authorsReadAuthorMeResponseTransformer = async (data: any): Promise<AuthorsReadAuthorMeResponse> => {
    data = authorPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const authorsUpdateAuthorMeResponseTransformer = async (data: any): Promise<AuthorsUpdateAuthorMeResponse> => {
    data = authorPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const authorsReadAuthorByIdResponseTransformer = async (data: any): Promise<AuthorsReadAuthorByIdResponse> => {
    data = authorPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const authorsUpdateAuthorResponseTransformer = async (data: any): Promise<AuthorsUpdateAuthorResponse> => {
    data = authorPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

const poemPublicWithAuthorAndTypeSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

const poemPublicWithAuthorSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

const poemPublicWithAllTheInfoSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    if (data.derived_poems) {
        data.derived_poems = data.derived_poems.map((item: any) => {
            return poemPublicWithAuthorAndTypeSchemaResponseTransformer(item);
        });
    }
    if (data.original) {
        data.original = poemPublicWithAuthorSchemaResponseTransformer(data.original);
    }
    return data;
};

const poemsPublicSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return poemPublicWithAllTheInfoSchemaResponseTransformer(item);
    });
    return data;
};

export const poemsReadPoemsResponseTransformer = async (data: any): Promise<PoemsReadPoemsResponse> => {
    data = poemsPublicSchemaResponseTransformer(data);
    return data;
};

export const poemsCreatePoemResponseTransformer = async (data: any): Promise<PoemsCreatePoemResponse> => {
    data = poemPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

export const poemsReadPoemsMeResponseTransformer = async (data: any): Promise<PoemsReadPoemsMeResponse> => {
    data = poemsPublicSchemaResponseTransformer(data);
    return data;
};

export const poemsReadPoemResponseTransformer = async (data: any): Promise<PoemsReadPoemResponse> => {
    data = poemPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

export const poemsUpdatePoemResponseTransformer = async (data: any): Promise<PoemsUpdatePoemResponse> => {
    data = poemPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

export const privateCreateUserResponseTransformer = async (data: any): Promise<PrivateCreateUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};