// This file is auto-generated by @hey-api/openapi-ts

import type { LoginTestTokenResponse, UsersReadUsersResponse, UsersCreateUserResponse, UsersReadUserMeResponse, UsersUpdateUserMeResponse, UsersRegisterUserResponse, UsersReadUserByIdResponse, UsersUpdateUserResponse, AuthorsReadAuthorsResponse, AuthorsCreateAuthorResponse, AuthorsReadAuthorByIdResponse, AuthorsUpdateAuthorResponse, PoemsReadPoemsResponse, PoemsCreatePoemResponse, PoemsReadRandomPoemResponse, PoemsReadPoemResponse, PoemsUpdatePoemResponse, CollectionsReadCollectionsResponse, CollectionsCreateCollectionResponse, CollectionsReadCollectionResponse, CollectionsUpdateCollectionResponse, CollectionsAddPoemToCollectionResponse } from './types.gen';

const authorPublicSchemaResponseTransformer = (data: any) => {
    if (data.birth_date) {
        data.birth_date = new Date(data.birth_date);
    }
    if (data.death_date) {
        data.death_date = new Date(data.death_date);
    }
    return data;
};

const collectionPublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

const userPublicSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.author) {
        data.author = authorPublicSchemaResponseTransformer(data.author);
    }
    if (data.collections) {
        data.collections = data.collections.map((item: any) => {
            return collectionPublicSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const loginTestTokenResponseTransformer = async (data: any): Promise<LoginTestTokenResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

const usersPublicSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return userPublicSchemaResponseTransformer(item);
    });
    return data;
};

export const usersReadUsersResponseTransformer = async (data: any): Promise<UsersReadUsersResponse> => {
    data = usersPublicSchemaResponseTransformer(data);
    return data;
};

export const usersCreateUserResponseTransformer = async (data: any): Promise<UsersCreateUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersReadUserMeResponseTransformer = async (data: any): Promise<UsersReadUserMeResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersUpdateUserMeResponseTransformer = async (data: any): Promise<UsersUpdateUserMeResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersRegisterUserResponseTransformer = async (data: any): Promise<UsersRegisterUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersReadUserByIdResponseTransformer = async (data: any): Promise<UsersReadUserByIdResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

export const usersUpdateUserResponseTransformer = async (data: any): Promise<UsersUpdateUserResponse> => {
    data = userPublicSchemaResponseTransformer(data);
    return data;
};

const poemPublicSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

const authorPublicWithPoemsSchemaResponseTransformer = (data: any) => {
    if (data.birth_date) {
        data.birth_date = new Date(data.birth_date);
    }
    if (data.death_date) {
        data.death_date = new Date(data.death_date);
    }
    if (data.poems) {
        data.poems = data.poems.map((item: any) => {
            return poemPublicSchemaResponseTransformer(item);
        });
    }
    return data;
};

const authorsPublicWithPoemsSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return authorPublicWithPoemsSchemaResponseTransformer(item);
    });
    return data;
};

export const authorsReadAuthorsResponseTransformer = async (data: any): Promise<AuthorsReadAuthorsResponse> => {
    data = authorsPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const authorsCreateAuthorResponseTransformer = async (data: any): Promise<AuthorsCreateAuthorResponse> => {
    data = authorPublicSchemaResponseTransformer(data);
    return data;
};

export const authorsReadAuthorByIdResponseTransformer = async (data: any): Promise<AuthorsReadAuthorByIdResponse> => {
    data = authorPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const authorsUpdateAuthorResponseTransformer = async (data: any): Promise<AuthorsUpdateAuthorResponse> => {
    data = authorPublicSchemaResponseTransformer(data);
    return data;
};

const poemPublicWithAllTheInfoSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    if (data.derived_poems) {
        data.derived_poems = data.derived_poems.map((item: any) => {
            return poemPublicSchemaResponseTransformer(item);
        });
    }
    if (data.original) {
        data.original = poemPublicSchemaResponseTransformer(data.original);
    }
    return data;
};

const poemsPublicWithAllTheInfoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return poemPublicWithAllTheInfoSchemaResponseTransformer(item);
    });
    return data;
};

export const poemsReadPoemsResponseTransformer = async (data: any): Promise<PoemsReadPoemsResponse> => {
    data = poemsPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

export const poemsCreatePoemResponseTransformer = async (data: any): Promise<PoemsCreatePoemResponse> => {
    data = poemPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

const poemRandomSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

export const poemsReadRandomPoemResponseTransformer = async (data: any): Promise<PoemsReadRandomPoemResponse> => {
    data = poemRandomSchemaResponseTransformer(data);
    return data;
};

export const poemsReadPoemResponseTransformer = async (data: any): Promise<PoemsReadPoemResponse> => {
    data = poemPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

export const poemsUpdatePoemResponseTransformer = async (data: any): Promise<PoemsUpdatePoemResponse> => {
    data = poemPublicWithAllTheInfoSchemaResponseTransformer(data);
    return data;
};

const collectionPublicWithPoemsSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    if (data.poems) {
        data.poems = data.poems.map((item: any) => {
            return poemPublicSchemaResponseTransformer(item);
        });
    }
    return data;
};

const collectionsPublicSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return collectionPublicWithPoemsSchemaResponseTransformer(item);
    });
    return data;
};

export const collectionsReadCollectionsResponseTransformer = async (data: any): Promise<CollectionsReadCollectionsResponse> => {
    data = collectionsPublicSchemaResponseTransformer(data);
    return data;
};

export const collectionsCreateCollectionResponseTransformer = async (data: any): Promise<CollectionsCreateCollectionResponse> => {
    data = collectionPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const collectionsReadCollectionResponseTransformer = async (data: any): Promise<CollectionsReadCollectionResponse> => {
    data = collectionPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const collectionsUpdateCollectionResponseTransformer = async (data: any): Promise<CollectionsUpdateCollectionResponse> => {
    data = collectionPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};

export const collectionsAddPoemToCollectionResponseTransformer = async (data: any): Promise<CollectionsAddPoemToCollectionResponse> => {
    data = collectionPublicWithPoemsSchemaResponseTransformer(data);
    return data;
};