// This file is auto-generated by @hey-api/openapi-ts

export type AuthorCreate = {
    full_name: string;
    birth_date?: Date | null;
};

export type AuthorPublic = {
    full_name: string;
    birth_date?: Date | null;
    id: string;
};

export type AuthorPublicBasic = {
    id: string;
    full_name: string;
};

export type AuthorPublicWithPoems = {
    full_name: string;
    birth_date?: Date | null;
    id: string;
    poems?: Array<PoemPublic>;
};

export type AuthorUpdate = {
    full_name?: string | null;
    birth_date?: Date | null;
};

export type AuthorsPublic = {
    data: Array<AuthorPublicBasic>;
    count: number;
};

export type AuthorsPublicWithPoems = {
    data: Array<AuthorPublicWithPoems>;
    count: number;
};

export type BodyLoginLoginAccessToken = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PoemCreate = {
    title: string;
    content: string;
    is_public?: boolean;
    show_author?: boolean;
    language?: string | null;
    type?: number | null;
    original_poem_id?: string | null;
    author_names?: Array<string> | null;
};

export type PoemPublic = {
    id: string;
    title: string;
    language?: string | null;
    created_at?: Date | null;
    updated_at?: Date | null;
    type?: number | null;
    is_public?: boolean;
    show_author?: boolean;
};

export type PoemPublicWithAllTheInfo = {
    id: string;
    title: string;
    language?: string | null;
    created_at?: Date | null;
    updated_at?: Date | null;
    type?: number | null;
    is_public?: boolean;
    show_author?: boolean;
    author_names?: Array<string>;
    author_ids?: Array<string>;
    content: string;
    derived_poems?: Array<PoemPublicWithAuthor>;
    original?: PoemPublicWithAuthor | null;
};

export type PoemPublicWithAuthor = {
    id: string;
    title: string;
    language?: string | null;
    created_at?: Date | null;
    updated_at?: Date | null;
    type?: number | null;
    is_public?: boolean;
    show_author?: boolean;
    author_names?: Array<string>;
    author_ids?: Array<string>;
};

export type PoemUpdate = {
    title?: string | null;
    content?: string | null;
    is_public?: boolean | null;
    show_author?: boolean | null;
    language?: string | null;
    author_names?: Array<string> | null;
    type?: number | null;
    original_poem_id?: string | null;
};

export type PoemsPublic = {
    data: Array<PoemPublicWithAuthor>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
    username: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    full_name?: string | null;
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    password: string;
};

export type UserPublic = {
    email: string;
    full_name?: string | null;
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    id: string;
    created_at?: Date | null;
    author_id?: string | null;
};

export type UserRegister = {
    email: string;
    password: string;
    username: string;
    full_name?: string | null;
};

export type UserUpdate = {
    email?: string | null;
    full_name?: string | null;
    username?: string | null;
    is_active?: boolean;
    is_superuser?: boolean;
    password?: string | null;
    author_id?: string | null;
};

export type UserUpdateMe = {
    full_name?: string | null;
    email?: string | null;
    username?: string | null;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type AuthorsReadAuthorsData = {
    body?: never;
    path?: never;
    query?: {
        order_by?: 'full_name' | 'birth_date' | 'poems';
        limit?: number;
        skip?: number;
        desc?: boolean;
        full_name?: string;
        birth_date?: string;
        poems?: string;
    };
    url: '/api/v1/authors';
};

export type AuthorsReadAuthorsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsReadAuthorsError = AuthorsReadAuthorsErrors[keyof AuthorsReadAuthorsErrors];

export type AuthorsReadAuthorsResponses = {
    /**
     * Successful Response
     */
    200: AuthorsPublic | AuthorsPublicWithPoems;
};

export type AuthorsReadAuthorsResponse = AuthorsReadAuthorsResponses[keyof AuthorsReadAuthorsResponses];

export type AuthorsCreateAuthorData = {
    body: AuthorCreate;
    path?: never;
    query?: never;
    url: '/api/v1/authors/';
};

export type AuthorsCreateAuthorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsCreateAuthorError = AuthorsCreateAuthorErrors[keyof AuthorsCreateAuthorErrors];

export type AuthorsCreateAuthorResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublic;
};

export type AuthorsCreateAuthorResponse = AuthorsCreateAuthorResponses[keyof AuthorsCreateAuthorResponses];

export type AuthorsDeleteAuthorData = {
    body?: never;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}';
};

export type AuthorsDeleteAuthorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsDeleteAuthorError = AuthorsDeleteAuthorErrors[keyof AuthorsDeleteAuthorErrors];

export type AuthorsDeleteAuthorResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AuthorsDeleteAuthorResponse = AuthorsDeleteAuthorResponses[keyof AuthorsDeleteAuthorResponses];

export type AuthorsReadAuthorByIdData = {
    body?: never;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}';
};

export type AuthorsReadAuthorByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsReadAuthorByIdError = AuthorsReadAuthorByIdErrors[keyof AuthorsReadAuthorByIdErrors];

export type AuthorsReadAuthorByIdResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublicWithPoems;
};

export type AuthorsReadAuthorByIdResponse = AuthorsReadAuthorByIdResponses[keyof AuthorsReadAuthorByIdResponses];

export type AuthorsUpdateAuthorData = {
    body: AuthorUpdate;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}';
};

export type AuthorsUpdateAuthorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsUpdateAuthorError = AuthorsUpdateAuthorErrors[keyof AuthorsUpdateAuthorErrors];

export type AuthorsUpdateAuthorResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublic;
};

export type AuthorsUpdateAuthorResponse = AuthorsUpdateAuthorResponses[keyof AuthorsUpdateAuthorResponses];

export type PoemsReadPoemsData = {
    body?: never;
    path?: never;
    query?: {
        order_by?: 'created_at' | 'updated_at' | 'title';
        limit?: number;
        skip?: number;
        desc?: boolean;
        title?: string;
        created_at?: string;
        updated_at?: string;
        verses?: string;
        type?: 'all' | 'version' | 'translation' | 'derived' | 'original' | '';
        language?: string;
    };
    url: '/api/v1/poems';
};

export type PoemsReadPoemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsReadPoemsError = PoemsReadPoemsErrors[keyof PoemsReadPoemsErrors];

export type PoemsReadPoemsResponses = {
    /**
     * Successful Response
     */
    200: PoemsPublic;
};

export type PoemsReadPoemsResponse = PoemsReadPoemsResponses[keyof PoemsReadPoemsResponses];

export type PoemsReadRandomPoemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/poems/random';
};

export type PoemsReadRandomPoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsReadRandomPoemResponse = PoemsReadRandomPoemResponses[keyof PoemsReadRandomPoemResponses];

export type PoemsDeletePoemData = {
    body?: never;
    path: {
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/poems/{poem_id}';
};

export type PoemsDeletePoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsDeletePoemError = PoemsDeletePoemErrors[keyof PoemsDeletePoemErrors];

export type PoemsDeletePoemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PoemsDeletePoemResponse = PoemsDeletePoemResponses[keyof PoemsDeletePoemResponses];

export type PoemsReadPoemData = {
    body?: never;
    path: {
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/poems/{poem_id}';
};

export type PoemsReadPoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsReadPoemError = PoemsReadPoemErrors[keyof PoemsReadPoemErrors];

export type PoemsReadPoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsReadPoemResponse = PoemsReadPoemResponses[keyof PoemsReadPoemResponses];

export type PoemsUpdatePoemData = {
    body: PoemUpdate;
    path: {
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/poems/{poem_id}';
};

export type PoemsUpdatePoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsUpdatePoemError = PoemsUpdatePoemErrors[keyof PoemsUpdatePoemErrors];

export type PoemsUpdatePoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsUpdatePoemResponse = PoemsUpdatePoemResponses[keyof PoemsUpdatePoemResponses];

export type PoemsCreatePoemData = {
    body: PoemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/poems/';
};

export type PoemsCreatePoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsCreatePoemError = PoemsCreatePoemErrors[keyof PoemsCreatePoemErrors];

export type PoemsCreatePoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsCreatePoemResponse = PoemsCreatePoemResponses[keyof PoemsCreatePoemResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};