// This file is auto-generated by @hey-api/openapi-ts

export type AuthorCreate = {
    full_name: string;
    birth_date?: Date | null;
    death_date?: Date | null;
};

export type AuthorPublic = {
    full_name: string;
    id: string;
    birth_date?: Date | null;
    death_date?: Date | null;
    user_id?: string | null;
};

export type AuthorPublicBasic = {
    full_name: string;
    id: string;
};

export type AuthorPublicWithPoems = {
    full_name: string;
    id: string;
    birth_date?: Date | null;
    death_date?: Date | null;
    user_id?: string | null;
    poems?: Array<PoemPublic>;
};

export type AuthorSearchParams = {
    author_order_by?: 'full_name' | 'birth_date' | 'poems' | 'death_date';
    author_limit?: number;
    author_skip?: number;
    author_desc?: boolean;
    author_full_name?: string;
    author_birth_date?: string;
    author_death_date?: string;
    author_poems?: string;
    author_basic?: boolean;
};

export type AuthorUpdate = {
    birth_date?: Date | null;
    full_name?: string | null;
    death_date?: Date | null;
};

export type AuthorUpdateBasic = {
    birth_date?: Date | null;
};

export type AuthorsPublic = {
    data: Array<AuthorPublic>;
    count: number;
};

export type AuthorsPublicWithPoems = {
    data: Array<AuthorPublicWithPoems>;
    count: number;
};

export type BodyAuthorsUploadAuthorPicture = {
    file: Blob | File;
};

export type BodyLoginLoginAccessToken = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyUsersUpdateUserMeProfilePicture = {
    image: Blob | File;
};

export type BodyUsersUpdateUserProfilePicture = {
    image: Blob | File;
};

export type CollectionCreate = {
    name: string;
    is_public?: boolean;
    description?: string | null;
    poem_ids?: Array<string>;
    user_id?: string | null;
};

export type CollectionPublic = {
    name: string;
    is_public?: boolean;
    id: string;
    username?: string | null;
    description?: string | null;
    created_at: Date | null;
    updated_at: Date | null;
};

export type CollectionPublicBasic = {
    name: string;
    is_public?: boolean;
    id: string;
    username?: string | null;
};

export type CollectionPublicWithPoems = {
    name: string;
    is_public?: boolean;
    id: string;
    username?: string | null;
    description?: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    poems?: Array<PoemPublic>;
    user_id: string;
};

export type CollectionSearchParams = {
    collection_limit?: number;
    collection_skip?: number;
    collection_desc?: boolean;
    collection_name?: string;
    collection_basic?: boolean;
};

export type CollectionUpdate = {
    name?: string | null;
    is_public?: boolean | null;
    description?: string | null;
    poem_ids?: Array<string> | null;
};

export type CollectionsPublic = {
    count: number;
    data: Array<CollectionPublicWithPoems>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PoemCreate = {
    title: string;
    content: string;
    description?: string | null;
    is_public?: boolean;
    show_author?: boolean;
    language?: string | null;
    type?: number | null;
    original_poem_id?: string | null;
    author_names?: Array<string> | null;
};

export type PoemPublic = {
    id: string;
    title: string;
    author_names?: Array<string>;
    is_public?: boolean;
    show_author?: boolean;
    description?: string | null;
    language?: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    type?: number | null;
    author_ids?: Array<string>;
};

export type PoemPublicBasic = {
    id: string;
    title: string;
    author_names?: Array<string>;
    is_public?: boolean;
    show_author?: boolean;
};

export type PoemPublicWithAllTheInfo = {
    id: string;
    title: string;
    author_names?: Array<string>;
    is_public?: boolean;
    show_author?: boolean;
    description?: string | null;
    language?: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    type?: number | null;
    author_ids?: Array<string>;
    content: string;
    derived_poems?: Array<PoemPublic>;
    original?: PoemPublic | null;
};

export type PoemRandom = {
    id: string;
    title: string;
    author_names?: Array<string>;
    is_public?: boolean;
    show_author?: boolean;
    description?: string | null;
    language?: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    type?: number | null;
    author_ids?: Array<string>;
    content: string;
};

export type PoemSearchParams = {
    poem_order_by?: 'created_at' | 'updated_at' | 'title';
    poem_limit?: number;
    poem_skip?: number;
    poem_desc?: boolean;
    poem_title?: string;
    poem_created_at?: string;
    poem_updated_at?: string;
    poem_verses?: string;
    poem_type?: 'all' | 'version' | 'translation' | 'derived' | 'original' | '';
    poem_language?: string;
    poem_basic?: boolean;
    poem_author?: string;
};

export type PoemUpdate = {
    title?: string | null;
    content?: string | null;
    description?: string | null;
    is_public?: boolean | null;
    show_author?: boolean | null;
    language?: string | null;
    author_names?: Array<string> | null;
    type?: number | null;
    original_poem_id?: string | null;
};

export type PoemsPublic = {
    data: Array<PoemPublic>;
    count: number;
};

export type PoemsPublicWithAllTheInfo = {
    data: Array<PoemPublicWithAllTheInfo>;
    count: number;
};

export type SearchParams = {
    search_type?: Array<'author' | 'poem' | 'collection' | 'user'>;
    author_params?: AuthorSearchParams | null;
    poem_params?: PoemSearchParams | null;
    collection_params?: CollectionSearchParams | null;
    user_params?: UserSearchParams | null;
};

export type SearchResult = {
    authors?: Array<AuthorPublicBasic> | AuthorsPublic;
    poems?: Array<PoemPublicBasic> | PoemsPublic;
    collections?: Array<CollectionPublicBasic> | CollectionsPublic;
    users?: Array<UserPublicBasic> | UsersPublic;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    full_name?: string | null;
    username: string;
    is_superuser?: boolean;
    is_verified?: boolean;
    password: string;
};

export type UserPublic = {
    email: string;
    full_name?: string | null;
    username: string;
    is_superuser?: boolean;
    is_verified?: boolean;
    id: string;
    created_at: Date | null;
    author_id?: string | null;
    author?: AuthorPublic | null;
    collections?: Array<CollectionPublic>;
};

export type UserPublicBasic = {
    id: string;
    username: string;
};

export type UserRegister = {
    email: string;
    password: string;
    username: string;
    full_name?: string | null;
};

export type UserSearchParams = {
    user_order_by?: 'full_name' | 'email' | 'username';
    user_limit?: number;
    user_skip?: number;
    user_desc?: boolean;
    user_name?: string;
    user_email?: string;
    user_full_name?: string;
    user_basic?: boolean;
};

export type UserUpdate = {
    email?: string | null;
    full_name?: string | null;
    username?: string | null;
    is_superuser?: boolean;
    is_verified?: boolean | null;
    password?: string | null;
    author_id?: string | null;
};

export type UserUpdateMe = {
    full_name?: string | null;
    email?: string | null;
    username?: string | null;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type VerifyToken = {
    token: string;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type LoginActivateAccountData = {
    body: VerifyToken;
    path?: never;
    query?: never;
    url: '/api/v1/activate-account/';
};

export type LoginActivateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginActivateAccountError = LoginActivateAccountErrors[keyof LoginActivateAccountErrors];

export type LoginActivateAccountResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginActivateAccountResponse = LoginActivateAccountResponses[keyof LoginActivateAccountResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersGetUserMeProfilePictureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/profile_picture';
};

export type UsersGetUserMeProfilePictureResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersUpdateUserMeProfilePictureData = {
    body: BodyUsersUpdateUserMeProfilePicture;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/profile_picture';
};

export type UsersUpdateUserMeProfilePictureErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeProfilePictureError = UsersUpdateUserMeProfilePictureErrors[keyof UsersUpdateUserMeProfilePictureErrors];

export type UsersUpdateUserMeProfilePictureResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdateUserMeProfilePictureResponse = UsersUpdateUserMeProfilePictureResponses[keyof UsersUpdateUserMeProfilePictureResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersGetUserProfilePictureData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/profile_picture';
};

export type UsersGetUserProfilePictureErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersGetUserProfilePictureError = UsersGetUserProfilePictureErrors[keyof UsersGetUserProfilePictureErrors];

export type UsersGetUserProfilePictureResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersUpdateUserProfilePictureData = {
    body: BodyUsersUpdateUserProfilePicture;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/profile_picture';
};

export type UsersUpdateUserProfilePictureErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserProfilePictureError = UsersUpdateUserProfilePictureErrors[keyof UsersUpdateUserProfilePictureErrors];

export type UsersUpdateUserProfilePictureResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdateUserProfilePictureResponse = UsersUpdateUserProfilePictureResponses[keyof UsersUpdateUserProfilePictureResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type AuthorsReadAuthorsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/authors/';
};

export type AuthorsReadAuthorsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsReadAuthorsError = AuthorsReadAuthorsErrors[keyof AuthorsReadAuthorsErrors];

export type AuthorsReadAuthorsResponses = {
    /**
     * Successful Response
     */
    200: AuthorsPublicWithPoems;
};

export type AuthorsReadAuthorsResponse = AuthorsReadAuthorsResponses[keyof AuthorsReadAuthorsResponses];

export type AuthorsCreateAuthorData = {
    body: AuthorCreate;
    path?: never;
    query?: never;
    url: '/api/v1/authors/';
};

export type AuthorsCreateAuthorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsCreateAuthorError = AuthorsCreateAuthorErrors[keyof AuthorsCreateAuthorErrors];

export type AuthorsCreateAuthorResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublic;
};

export type AuthorsCreateAuthorResponse = AuthorsCreateAuthorResponses[keyof AuthorsCreateAuthorResponses];

export type AuthorsUpdateAuthorMeData = {
    body: AuthorUpdateBasic;
    path?: never;
    query?: never;
    url: '/api/v1/authors/me';
};

export type AuthorsUpdateAuthorMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsUpdateAuthorMeError = AuthorsUpdateAuthorMeErrors[keyof AuthorsUpdateAuthorMeErrors];

export type AuthorsUpdateAuthorMeResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublic;
};

export type AuthorsUpdateAuthorMeResponse = AuthorsUpdateAuthorMeResponses[keyof AuthorsUpdateAuthorMeResponses];

export type AuthorsDeleteAuthorData = {
    body?: never;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}';
};

export type AuthorsDeleteAuthorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsDeleteAuthorError = AuthorsDeleteAuthorErrors[keyof AuthorsDeleteAuthorErrors];

export type AuthorsDeleteAuthorResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AuthorsDeleteAuthorResponse = AuthorsDeleteAuthorResponses[keyof AuthorsDeleteAuthorResponses];

export type AuthorsReadAuthorByIdData = {
    body?: never;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}';
};

export type AuthorsReadAuthorByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsReadAuthorByIdError = AuthorsReadAuthorByIdErrors[keyof AuthorsReadAuthorByIdErrors];

export type AuthorsReadAuthorByIdResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublicWithPoems;
};

export type AuthorsReadAuthorByIdResponse = AuthorsReadAuthorByIdResponses[keyof AuthorsReadAuthorByIdResponses];

export type AuthorsUpdateAuthorData = {
    body: AuthorUpdate;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}';
};

export type AuthorsUpdateAuthorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsUpdateAuthorError = AuthorsUpdateAuthorErrors[keyof AuthorsUpdateAuthorErrors];

export type AuthorsUpdateAuthorResponses = {
    /**
     * Successful Response
     */
    200: AuthorPublic;
};

export type AuthorsUpdateAuthorResponse = AuthorsUpdateAuthorResponses[keyof AuthorsUpdateAuthorResponses];

export type AuthorsGetAuthorPictureData = {
    body?: never;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}/picture';
};

export type AuthorsGetAuthorPictureErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsGetAuthorPictureError = AuthorsGetAuthorPictureErrors[keyof AuthorsGetAuthorPictureErrors];

export type AuthorsGetAuthorPictureResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthorsUploadAuthorPictureData = {
    body: BodyAuthorsUploadAuthorPicture;
    path: {
        author_id: string;
    };
    query?: never;
    url: '/api/v1/authors/{author_id}/picture';
};

export type AuthorsUploadAuthorPictureErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorsUploadAuthorPictureError = AuthorsUploadAuthorPictureErrors[keyof AuthorsUploadAuthorPictureErrors];

export type AuthorsUploadAuthorPictureResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AuthorsUploadAuthorPictureResponse = AuthorsUploadAuthorPictureResponses[keyof AuthorsUploadAuthorPictureResponses];

export type PoemsReadPoemsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/poems/';
};

export type PoemsReadPoemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsReadPoemsError = PoemsReadPoemsErrors[keyof PoemsReadPoemsErrors];

export type PoemsReadPoemsResponses = {
    /**
     * Successful Response
     */
    200: PoemsPublicWithAllTheInfo;
};

export type PoemsReadPoemsResponse = PoemsReadPoemsResponses[keyof PoemsReadPoemsResponses];

export type PoemsCreatePoemData = {
    body: PoemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/poems/';
};

export type PoemsCreatePoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsCreatePoemError = PoemsCreatePoemErrors[keyof PoemsCreatePoemErrors];

export type PoemsCreatePoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsCreatePoemResponse = PoemsCreatePoemResponses[keyof PoemsCreatePoemResponses];

export type PoemsReadRandomPoemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/poems/random';
};

export type PoemsReadRandomPoemResponses = {
    /**
     * Successful Response
     */
    200: PoemRandom;
};

export type PoemsReadRandomPoemResponse = PoemsReadRandomPoemResponses[keyof PoemsReadRandomPoemResponses];

export type PoemsDeletePoemData = {
    body?: never;
    path: {
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/poems/{poem_id}';
};

export type PoemsDeletePoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsDeletePoemError = PoemsDeletePoemErrors[keyof PoemsDeletePoemErrors];

export type PoemsDeletePoemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PoemsDeletePoemResponse = PoemsDeletePoemResponses[keyof PoemsDeletePoemResponses];

export type PoemsReadPoemData = {
    body?: never;
    path: {
        poem_id: string;
    };
    query?: {
        parse?: boolean;
    };
    url: '/api/v1/poems/{poem_id}';
};

export type PoemsReadPoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsReadPoemError = PoemsReadPoemErrors[keyof PoemsReadPoemErrors];

export type PoemsReadPoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsReadPoemResponse = PoemsReadPoemResponses[keyof PoemsReadPoemResponses];

export type PoemsUpdatePoemData = {
    body: PoemUpdate;
    path: {
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/poems/{poem_id}';
};

export type PoemsUpdatePoemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PoemsUpdatePoemError = PoemsUpdatePoemErrors[keyof PoemsUpdatePoemErrors];

export type PoemsUpdatePoemResponses = {
    /**
     * Successful Response
     */
    200: PoemPublicWithAllTheInfo;
};

export type PoemsUpdatePoemResponse = PoemsUpdatePoemResponses[keyof PoemsUpdatePoemResponses];

export type CollectionsReadCollectionsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/collections/';
};

export type CollectionsReadCollectionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsReadCollectionsError = CollectionsReadCollectionsErrors[keyof CollectionsReadCollectionsErrors];

export type CollectionsReadCollectionsResponses = {
    /**
     * Successful Response
     */
    200: CollectionsPublic;
};

export type CollectionsReadCollectionsResponse = CollectionsReadCollectionsResponses[keyof CollectionsReadCollectionsResponses];

export type CollectionsCreateCollectionData = {
    body: CollectionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/collections/';
};

export type CollectionsCreateCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsCreateCollectionError = CollectionsCreateCollectionErrors[keyof CollectionsCreateCollectionErrors];

export type CollectionsCreateCollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionPublicWithPoems;
};

export type CollectionsCreateCollectionResponse = CollectionsCreateCollectionResponses[keyof CollectionsCreateCollectionResponses];

export type CollectionsDeleteCollectionData = {
    body?: never;
    path: {
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}';
};

export type CollectionsDeleteCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsDeleteCollectionError = CollectionsDeleteCollectionErrors[keyof CollectionsDeleteCollectionErrors];

export type CollectionsDeleteCollectionResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CollectionsDeleteCollectionResponse = CollectionsDeleteCollectionResponses[keyof CollectionsDeleteCollectionResponses];

export type CollectionsReadCollectionData = {
    body?: never;
    path: {
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}';
};

export type CollectionsReadCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsReadCollectionError = CollectionsReadCollectionErrors[keyof CollectionsReadCollectionErrors];

export type CollectionsReadCollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionPublicWithPoems;
};

export type CollectionsReadCollectionResponse = CollectionsReadCollectionResponses[keyof CollectionsReadCollectionResponses];

export type CollectionsUpdateCollectionData = {
    body: CollectionUpdate;
    path: {
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}';
};

export type CollectionsUpdateCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsUpdateCollectionError = CollectionsUpdateCollectionErrors[keyof CollectionsUpdateCollectionErrors];

export type CollectionsUpdateCollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionPublicWithPoems;
};

export type CollectionsUpdateCollectionResponse = CollectionsUpdateCollectionResponses[keyof CollectionsUpdateCollectionResponses];

export type CollectionsRemovePoemFromCollectionData = {
    body?: never;
    path: {
        collection_id: string;
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/poems/{poem_id}';
};

export type CollectionsRemovePoemFromCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsRemovePoemFromCollectionError = CollectionsRemovePoemFromCollectionErrors[keyof CollectionsRemovePoemFromCollectionErrors];

export type CollectionsRemovePoemFromCollectionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CollectionsAddPoemToCollectionData = {
    body?: never;
    path: {
        collection_id: string;
        poem_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/poems/{poem_id}';
};

export type CollectionsAddPoemToCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionsAddPoemToCollectionError = CollectionsAddPoemToCollectionErrors[keyof CollectionsAddPoemToCollectionErrors];

export type CollectionsAddPoemToCollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionPublicWithPoems;
};

export type CollectionsAddPoemToCollectionResponse = CollectionsAddPoemToCollectionResponses[keyof CollectionsAddPoemToCollectionResponses];

export type SearchSearchData = {
    body: SearchParams;
    path?: never;
    query?: never;
    url: '/api/v1/search';
};

export type SearchSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSearchError = SearchSearchErrors[keyof SearchSearchErrors];

export type SearchSearchResponses = {
    /**
     * Successful Response
     */
    200: SearchResult;
};

export type SearchSearchResponse = SearchSearchResponses[keyof SearchSearchResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};